# Generated by Django 5.2.5 on 2025-09-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='M365Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(max_length=64)),
                ('client_id', models.CharField(max_length=64)),
                ('client_secret', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Microsoft 365 Configuration',
                'verbose_name_plural': 'Microsoft 365 Configuration',
            },
        ),
    ]
