# Generated by Django 5.2.5 on 2025-09-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m365', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='m365config',
            name='sharepoint_hostname',
            field=models.CharField(blank=True, help_text='e.g., contoso.sharepoint.com', max_length=255),
        ),
    ]
