# Generated by Django 5.2.5 on 2025-09-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m365', '0002_m365config_sharepoint_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='m365config',
            name='timesheet_list_name',
            field=models.CharField(default='timesheet', help_text='Display name of the timesheet list', max_length=255),
        ),
        migrations.AddField(
            model_name='m365config',
            name='timesheet_site_path',
            field=models.CharField(blank=True, help_text='Site path for the timesheet list, e.g., /sites/TeamA', max_length=255),
        ),
    ]
